/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Vendor = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'phone' : IDL.Text,
});
export const City = IDL.Text;
export const State = IDL.Text;
export const Latitude = IDL.Float64;
export const Longitude = IDL.Float64;
export const Location = IDL.Record({ 'lat' : Latitude, 'lng' : Longitude });
export const ListingInput = IDL.Record({
  'categoryId' : IDL.Nat,
  'city' : City,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'state' : State,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'location' : Location,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'phone' : IDL.Text,
});
export const DistanceKm = IDL.Float64;
export const SortBy = IDL.Variant({
  'byName' : IDL.Null,
  'byDistance' : IDL.Null,
});
export const Time = IDL.Int;
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'status' : ListingStatus,
  'owner' : IDL.Principal,
  'city' : City,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'createdTime' : Time,
  'website' : IDL.Text,
  'state' : State,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'location' : Location,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addVendor' : IDL.Func([Vendor], [], []),
  'adminDeleteListing' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateListing' : IDL.Func([IDL.Nat, ListingInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
  'claimFirstAdminRole' : IDL.Func([], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'deletePendingListingsRange' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'forceResetAdmin' : IDL.Func([], [], []),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getListingsByCategoryAndLocation' : IDL.Func(
      [IDL.Nat, Location, DistanceKm, SortBy],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getPendingListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListingsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  'submitListing' : IDL.Func([ListingInput], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, Category], [], []),
  'updateListing' : IDL.Func([IDL.Nat, ListingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Vendor = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const City = IDL.Text;
  const State = IDL.Text;
  const Latitude = IDL.Float64;
  const Longitude = IDL.Float64;
  const Location = IDL.Record({ 'lat' : Latitude, 'lng' : Longitude });
  const ListingInput = IDL.Record({
    'categoryId' : IDL.Nat,
    'city' : City,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'state' : State,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'location' : Location,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DistanceKm = IDL.Float64;
  const SortBy = IDL.Variant({ 'byName' : IDL.Null, 'byDistance' : IDL.Null });
  const Time = IDL.Int;
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'status' : ListingStatus,
    'owner' : IDL.Principal,
    'city' : City,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'createdTime' : Time,
    'website' : IDL.Text,
    'state' : State,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'location' : Location,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addVendor' : IDL.Func([Vendor], [], []),
    'adminDeleteListing' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateListing' : IDL.Func([IDL.Nat, ListingInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeListingStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
    'claimFirstAdminRole' : IDL.Func([], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'deletePendingListingsRange' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'forceResetAdmin' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getListingsByCategoryAndLocation' : IDL.Func(
        [IDL.Nat, Location, DistanceKm, SortBy],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getPendingListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListingsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'submitListing' : IDL.Func([ListingInput], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, Category], [], []),
    'updateListing' : IDL.Func([IDL.Nat, ListingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };