/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type City = string;
export type DistanceKm = number;
export type Latitude = number;
export interface Listing {
  'id' : bigint,
  'categoryId' : bigint,
  'status' : ListingStatus,
  'owner' : Principal,
  'city' : City,
  'name' : string,
  'description' : string,
  'photoIds' : Array<string>,
  'createdTime' : Time,
  'website' : string,
  'state' : State,
  'address' : string,
  'phone' : string,
  'location' : Location,
}
export interface ListingInput {
  'categoryId' : bigint,
  'city' : City,
  'name' : string,
  'description' : string,
  'photoIds' : Array<string>,
  'website' : string,
  'state' : State,
  'address' : string,
  'phone' : string,
  'location' : Location,
}
export type ListingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Location { 'lat' : Latitude, 'lng' : Longitude }
export type Longitude = number;
export type SortBy = { 'byName' : null } |
  { 'byDistance' : null };
export type State = string;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'businessName' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'principal' : Principal,
  'name' : string,
  'businessName' : string,
  'phone' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addVendor' : ActorMethod<[Vendor], undefined>,
  'adminDeleteListing' : ActorMethod<[bigint], undefined>,
  'adminUpdateListing' : ActorMethod<[bigint, ListingInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeListingStatus' : ActorMethod<[bigint, ListingStatus], undefined>,
  'claimFirstAdminRole' : ActorMethod<[], boolean>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'deletePendingListingsRange' : ActorMethod<[bigint, bigint], undefined>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getListingsByCategoryAndLocation' : ActorMethod<
    [bigint, Location, DistanceKm, SortBy],
    Array<Listing>
  >,
  'getPendingListings' : ActorMethod<[], Array<Listing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByCity' : ActorMethod<[string], Array<Listing>>,
  'submitListing' : ActorMethod<[ListingInput], undefined>,
  'updateCategory' : ActorMethod<[bigint, Category], undefined>,
  'updateListing' : ActorMethod<[bigint, ListingInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
